version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: 'Setting firebase tools'
          command: 'npm install -g firebase-tools'
      - run:
          name: 'build project 1'
          command: 'bundle exec jekyll build --verbose'
      - run:
          name: 'Deploy'
          command: 'firebase deploy --token=$FIREBASE_TOKEN --non-interactive'