version: 2
jobs:
  build:
    docker:
      - image: 'circleci/ruby:2.6.3-node-browsers'
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: 'Setting firebase tools'
          command: 'npm install firebase-tools'
      - run:
          name: 'isntall project 1'
          command: 'gem install jekyll bundler'
      - run:
          name: 'isntall project 2'
          command: 'gem install'
      - run:
          name: 'build project 1'
          command: 'bundle exec jekyll build --verbose'
      - run:
          name: 'Deploy'
          command: 'firebase deploy --token=$FIREBASE_TOKEN --non-interactive'